### PR TITLE
Make the executables customizable.

### LINKED ISSUE #5: Usage on Windows
First let me thank you for the interesting project. Unfortunately I could not get it to work for my use case. For now I have tried to get it to run on a Windows machine to compile remotely on a Linux machine. What is currently missing is a way to specify the binaries to use: Either you would need customizable variables to set the exact path to 'rsync' and 'expect' or at least you would have to handle the necessary '.exe' extension on Windows. I put 'rsync' and 'expect' into my exec-path, but they were not found, probably because the '.exe' suffix is missing.

### PR DESCRIPTION
**Pull request by kenhuang-io**
Try to fix #5

### CODE REVIEW

**Comment by martin5233** [comment]
Thanks for the quick fix. This prevents the problem with not finding the executables, however I stumbled into the next problem now:
I tried to use rsync either from cygwin or from mingw, but in both cases an error occurs. The error is, that rsync interprets the source directory as a remote directory, because it contains a drive letter with a colon. For Cygwin it would be possible to use /cygdrive/c/... instead of c:/..., but the source path comes directly from Emacs' default-directory, which contains the driver letter with the colon. To make your package work on Windows with one of these two rsync versions, you would need some sort of mapping similar to ppcompile-path-mapping-alist, but for forward-mapping paths, before handing them to rsync.

**Comment by kenhuang-io** [comment]
So you mean that `rsync` can only accept paths like `/cygdrive/c/`, and since you run a native Emacs, i.e. not in Cygwin or MinGW, the `default-directory` is like `C:/`, which breaks `rsync`?

BTW, if you toggle debugging by `M-x ppcompile-toggle-debug`, and try the commands printed in the `*Message*` buffer manually, does it work in the first place? (Set the password in the `PPCOMPILE_PASSWORD` env for the expect script.)

**Comment by martin5233** [comment]
Yes, you are right. I tried to call rsync by hand and I get exactly the same message, if I pass it a path containing a drive letter and a colon as source. So it's not really a problem of your package, but that rsync is really a Unix tool, which requires special treatment with respect to paths under Windows.

**Comment by kenhuang-io** [comment]
I must admit that it's not easy to set up these tools on Windows, I would recommend you to run a Linux on a VM guest on Windows if you like, it saves much effort.

If you must stick with Windows, maybe there are some native rsync clients outside? Also, I don't know how well `expect` works on Windows, maybe it has some problem too.

**Comment by martin5233** [comment]
I normally work under Linux, but now I'm stuck in home office with only a Windows laptop. Therefore I would have liked to get this running. Using a VM is not really an option in my case. I will try another rsync implementation in the next days, maybe we are lucky with a different one. Thanks for you efforts anyway.

**Comment by kenhuang-io** [comment]
Good luck :)

And if there are things that can be done here, just let me know.

**Comment by kenhuang-io** [comment]
I am merging this now, feel free to open another issue or reopen it if necessary.

**Pull request merged**
